/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.77
 * Generated at: 2017-10-04 03:16:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Login to E-Family</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<form>\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t\t<tr><td colspan=\"2\">Login to E-Family</td></tr>\r\n");
      out.write("\t\t\t<tr><td>User Name: </td><td><input type=\"text\" name=\"userId\" id=\"userId\"/></td></tr>\r\n");
      out.write("\t\t\t<tr><td>Password: </td><td><input type=\"password\" name=\"password\" id = \"password\"/></td></tr>\r\n");
      out.write("\t\t\t<tr><td colspan=\"2\"><input type=\"button\" onClick=\"login()\" value=\"Login\"/></td></tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<span id=\"loginResult\"></span>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t\r\n");
      out.write("\t<script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\twindow.onload = initPage;\r\n");
      out.write("\t\tvar request = false;\r\n");
      out.write("\r\n");
      out.write("\t\tfunction initPage() {\r\n");
      out.write("\t\t\ttry {\r\n");
      out.write("\t\t\t\trequest = new XMLHttpRequest();\r\n");
      out.write("\t\t\t} catch (trymicrosoft) {\r\n");
      out.write("\t\t\t\ttry {\r\n");
      out.write("\t\t\t\t\trequest = new ActiveXObject(\"Msxml2.XMLHTTP\");\r\n");
      out.write("\t\t\t\t} catch (e) {\r\n");
      out.write("\t\t\t\t\ttry {\r\n");
      out.write("\t\t\t\t\t\trequest = new ActiveXObject(\"Microsoft.XMLHTTP\");\r\n");
      out.write("\t\t\t\t\t} catch (failed) {\r\n");
      out.write("\t\t\t\t\t\trequest = false;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif (!request)\r\n");
      out.write("\t\t\t\talert(\"Error initializing XMLHttpRequest!\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction login() {\r\n");
      out.write("\t\t\tif (request == null) {\r\n");
      out.write("\t\t\t\talert(\"Unable to create request!\");\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t// Clear loginResult\r\n");
      out.write("\t\t\tdocument.getElementById(\"loginResult\").innerHTML = \"\";\r\n");
      out.write("\t\t\tvar userId = document.getElementById(\"userId\").value;\r\n");
      out.write("\t\t\tvar password = document.getElementById(\"password\").value;\r\n");
      out.write("\t\t\trequest.open(\"GET\", \"auth/loginAuth.do?userId=\" + escape(userId) + \"&password=\" + escape(password), true);\r\n");
      out.write("\t\t\trequest.onreadystatechange = showLoginResult;\r\n");
      out.write("\t\t\trequest.send(null);\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction showLoginResult() {\r\n");
      out.write("\t\t\tif (request.readyState == 4) {\r\n");
      out.write("\t\t\t\tif (request.status == 200) {\r\n");
      out.write("\t\t\t\t\twindow.location.href = \"home.do\";\r\n");
      out.write("\t\t\t\t} else if (request.status == 404) {\r\n");
      out.write("\t\t\t\t\talert(\"Requested URL is not found.\");\r\n");
      out.write("\t\t\t\t} else if (request.status == 403) {\r\n");
      out.write("\t\t\t\t\talert(\"Access denied.\");\r\n");
      out.write("\t\t\t\t} else if (request.status == 401) {\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"loginResult\").innerHTML = request.responseText.replace('\"', '').replace('\"', '');\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"loginResult\").innerHTML = request.status;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
