TRUNCATE TABLE ROLE;

INSERT INTO LOGIN_USER (   USER_ID,   USER_NAME,   ROLE_ID,   PASSWORD,   LAST_LOGIN_DATE,   REGIST_DATE,   REGIST_PNAME,   LAST_UPDATE_DATE,   LAST_UPDATE_PNAME ) VALUES (   'xueyu',   'Xue Yu',   'ADMIN',   'xueyup@ssw0rd',   NULL,   TO_TIMESTAMP('2017-09-28 00:00:00.000','YYYY-MM-DD HH24:MI:SS.FF'),   'SYSTEM',   NULL,   NULL );
INSERT INTO LOGIN_USER (   USER_ID,   USER_NAME,   ROLE_ID,   PASSWORD,   LAST_LOGIN_DATE,   REGIST_DATE,   REGIST_PNAME,   LAST_UPDATE_DATE,   LAST_UPDATE_PNAME ) VALUES (   'sulirui',   'Su Lirui',   'ADMIN',   'suliruip@ssw0rd',   NULL,   TO_TIMESTAMP('2017-09-28 00:00:00.000','YYYY-MM-DD HH24:MI:SS.FF'),   'SYSTEM',   NULL,   NULL );
INSERT INTO LOGIN_USER (   USER_ID,   USER_NAME,   ROLE_ID,   PASSWORD,   LAST_LOGIN_DATE,   REGIST_DATE,   REGIST_PNAME,   LAST_UPDATE_DATE,   LAST_UPDATE_PNAME ) VALUES (   'dev',   'Development User',   'DEV',   'dev',   NULL,   TO_TIMESTAMP('2017-09-28 00:00:00.000','YYYY-MM-DD HH24:MI:SS.FF'),   'SYSTEM',   NULL,   NULL );

COMMENT;