DROP TABLE LOGIN_USER;

CREATE TABLE LOGIN_USER (
	USER_ID VARCHAR2 (50) NOT NULL PRIMARY KEY,
	USER_NAME VARCHAR2 (100),
	ROLE_ID VARCHAR2 (10) NOT NULL,
	LAST_LOGIN_DATE DATE,
	REGIST_DATE DATE DEFAULT SYSDATE,
	REGIST_PNAME VARCHAR2 (50),
	LAST_UPDATE_DATE DATE DEFAULT SYSDATE,
	LAST_UPDATE_PNAME VARCHAR2 (50)
);
