DROP TABLE EVENT;

CREATE TABLE EVENT (
	EVENT_ID VARCHAR2 (10) NOT NULL PRIMARY KEY,
	TITLE VARCHAR2 (1024) NOT NULL,
	LOCATION VARCHAR2 (1024),
	START_DATE DATE NOT NULL,
	END_DATE DATE NOT NULL,
	IS_ALL_DAY VARCHAR2 (1) NOT NULL,
	REGIST_BY VARCHAR2 (50),
	UPDATE_BY VARCHAR2 (50),
	REGIST_DATE DATE DEFAULT SYSDATE,
	REGIST_PNAME VARCHAR2 (50),
	LAST_UPDATE_DATE DATE DEFAULT SYSDATE,
	LAST_UPDATE_PNAME VARCHAR2 (50)
);

DROP SEQUENCE EVENT_SEQ;
CREATE SEQUENCE EVENT_SEQ MINVALUE 1 MAXVALUE 999999 START WITH 1 INCREMENT BY 1 NOCACHE;
