DROP TABLE ROLE;

CREATE TABLE ROLE (
	ROLE_ID VARCHAR2 (50) NOT NULL PRIMARY KEY,
	ROLE_NAME VARCHAR2 (100),
	ADMIN_FLAG VARCHAR2 (1) DEFAULT ('0') NOT NULL,
	GUEST_FLAG VARCHAR2 (1) DEFAULT ('1') NOT NULL,
	EXPIRY_DATE DATE NOT NULL,
	REGIST_DATE DATE DEFAULT SYSDATE,
	REGIST_PNAME VARCHAR2 (50),
	LAST_UPDATE_DATE DATE DEFAULT SYSDATE,
	LAST_UPDATE_PNAME VARCHAR2 (50)
);
